#!/bin/bash

__reset="\e[0m"

echo -ne " \t"
for bg in $(seq 0 7); do
  echo -n "  4${bg}m   "
done
echo
for fg in $(seq 0 7); do
  echo -ne "   3$fg \t"
  for bg in $(seq 0 7); do
    echo -ne "\e[4${bg}m\e[3${fg}m  gYw  $__reset "
  done
  echo

  echo -ne " 1;3$fg \t"
  for bg in $(seq 0 7); do
    echo -ne "\e[4${bg}m\e[1;3${fg}m  gYw  $__reset "
  done
  echo
done
echo -ne "$__reset"
